openapi: 3.0.1
info:
  title: alunos
  description: API Definition of alunos
  version: 1.0.0
servers:
- url: http://localhost:8290/alunos
paths:
  /:
    get:
      responses:
        default:
          description: Default response
